### ISSUE TITLE
Neosnippet always expand one parameter from lsp

### ISSUE THREAD

**Issue by amikai** [Shougo/neosnippet.vim#496] opened 2020-06-17 01:27 UTC
When i using neosnippet completion for parameter, no matter how many parameter it have, it always expand one parameter. See the follwing two screenshot.
1. screen shot 1:  `io.ReadFull` has two parameter
![image](https://user-images.githubusercontent.com/13815956/84843720-3e3ef200-b07b-11ea-98ea-9a4c0f6e12b9.png)
2. screen shot2: `abc` has three parameter
![image](https://user-images.githubusercontent.com/13815956/84843968-e3f26100-b07b-11ea-9309-4115d0390d46.png)

So i print the `lsp_item` at this [line](https://github.com/Shougo/neosnippet.vim/blob/master/autoload/neosnippet/helpers.vim#L249
), i found `'newText':'abc(${1:})'` (screenshot2 example)

**Comment by Shougo** [comment] 2020-06-17 02:25
Reproduced.  But it is not neosnippet problem.
Because, gopls's result is only one parameter.

It should be reported in gopls.
Closing.

Note: Other LSP like pyls works for me instead.

**Closed by Shougo** 2020-06-17 02:25 UTC

**Comment by Shougo** [comment] 2020-06-17 02:27
And, you should provide more information to reproduce the problem.
You have not upload reproduce instructions.
We have not ESP skills.

**Comment by amikai** [comment] 2020-06-17 02:51
Sorry for that, i will give detail steps next time.

**Comment by Shougo** [comment] 2020-06-17 03:08
OK

**Comment by Shougo** [comment] 2020-06-17 12:50
OK.  It is not gopls problem probably.
You need to configure gopls like this.

```vim
lua require'nvim_lsp'.gopls.setup{
      \ init_options = {
      \   usePlaceholders = true,
      \ }
      \}
```

Note: It is suggested by @hrth7th.

**Comment by amikai** [comment] 2020-06-17 14:50
It work. THX
