### ISSUE TITLE
Some snippets do not work

### ISSUE THREAD

**Issue by ToruIwashita** [Shougo/neosnippet.vim#427] opened 2018-04-17 05:29 UTC
@jsit Some snippets stopped working on this pull request.

https://github.com/Shougo/neosnippet.vim/pull/419

What I confirmed is snippets starting from one character as follows.

https://github.com/honza/vim-snippets/blob/d081fa5117acdd972bd0a3ec1c0424e79ef6121e/snippets/vim.snippets#L11-L20

As a result of checking, it seems that one character snippet depends on the following code, so it seems that it is not enough to add a suffix only when duplication exists.

https://github.com/Shougo/neosnippet.vim/blob/f514e3be28839ef6182c4e6943ed01abcc01184b/autoload/neosnippet/parser.vim#L150-L153

**Comment by Shougo** [comment] 2018-04-17 23:37
I will check the issue.
Please upload the minimal vimrc and the reproduce ways from Vim starting.

**Comment by Shougo** [comment] 2018-04-18 14:00
I have tested the minimal environment and it works.
I cannot reproduce the problem.
Closing.

**Closed by Shougo** 2018-04-18 14:00 UTC
Labels: Bug, cannot reproduce, reproduce instructions needed
